/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ui;

import static Ui.frmEditarJornada.lblId;
import static Ui.infrmAgregar.jTable1;
import static Ui.infrmAgregar.validateEmail;
import static Ui.infrmAgregar.validateTelephone;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import logic.clsEmpleados;
import logic.clsGestorAdmin;
import logic.clsGestorJornada;
/**
 *
 * @author INVENIO122
 */
public class EditarUsuario extends javax.swing.JFrame {

    clsGestorAdmin gestorAdmin;
    clsEmpleados empleados;
    ResultSet rs;
    public EditarUsuario() {
         
        gestorAdmin = new clsGestorAdmin();
      empleados = new clsEmpleados();
        initComponents();
          rs = null;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tvID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboTipoUsuario = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        btEditar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edición de Datos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        tvID.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tvID.setText("Cedula:");

        tfID.setEditable(false);
        tfID.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        tfNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        tfApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Usuario:");

        cboTipoUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Empleado" }));
        cboTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Correo:");

        tfEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Telefono:");

        tfTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Usuario:");

        tfUser.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña:");

        tfPass.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(tvID)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPass)
                    .addComponent(tfUser)
                    .addComponent(tfTelefono)
                    .addComponent(tfEmail)
                    .addComponent(tfNombre)
                    .addComponent(cboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellido)
                    .addComponent(tfID)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tvID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btEditar.setText("Actualizar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));

        lbl.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lbl.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(155, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl)
                                .addGap(92, 92, 92))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(9, 9, 9)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoUsuarioActionPerformed
        if (cboTipoUsuario.getSelectedItem() == "Administrador"){
            lbl.setText("1");
        }else{
            lbl.setText("2");
        }
    }//GEN-LAST:event_cboTipoUsuarioActionPerformed

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
             
  gestorAdmin.conectarBD();
     rs = gestorAdmin.buscarporid(Integer.parseInt(tfID.getText()));
        try {
            if (rs.next()) {
                
               
                 tfNombre.setText(rs.getString("nombre"));
                tfApellido.setText(rs.getString("apellidos"));
                 tfUser.setText(rs.getString("usuario"));
                  tfEmail.setText(rs.getString("email"));
                  tfPass.setText(rs.getString("password"));
                  tfTelefono.setText(rs.getString("telefono"));
                  lbl.setText(rs.getString("idtipousuario"));
                   
                   
            } } catch (SQLException ex) {
            Logger.getLogger(EditarUsuario.class.getName()).log(Level.SEVERE, null, ex);
   }   gestorAdmin.desconectarBD();   
   rs = null ;
   
    if ("1".equals(lbl.getText())){
            cboTipoUsuario.setSelectedItem("Administrador");
        }else{
            cboTipoUsuario.setSelectedItem("Empleado");
        }
//    if(lbl.getText() == ""){
//        JOptionPane.showInputDialog("No se obtuvo el tipo de usuario, llamar al creador del software");
//            }
   
    }//GEN-LAST:event_formWindowActivated

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
  
  if (validarDatos().equals("")) {
 empleados = new clsEmpleados();
            empleados.setIdUsuario(Integer.parseInt(tfID.getText()));
            empleados.setNombre(tfNombre.getText());
            empleados.setApellido(tfApellido.getText());
            empleados.setTipo(Integer.parseInt(lbl.getText()));
            empleados.setEmail(tfEmail.getText());
            empleados.setTelefono(tfTelefono.getText());
            empleados.setUsuario(tfUser.getText());
            empleados.setPassword(tfPass.getText());
            gestorAdmin.conectarBD();
            rs = gestorAdmin.buscarUsuario(Integer.parseInt(tfID.getText()));
            try {
                if (rs.next()) {
                    gestorAdmin.editarUsuario(empleados);
                    JOptionPane.showMessageDialog(rootPane, "La información del empleado "+empleados.getNombre() + " ha sido editado (a) exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cedula no encontrada");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
           
            gestorAdmin.desconectarBD();
 this.dispose();
  }else {
            JOptionPane.showMessageDialog(rootPane, validarDatos());
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
          gestorAdmin.conectarBD();
        ResultSet sr = gestorAdmin.TodosUsuarios();
        if (sr != null) {
            jTable1.setModel(gestorAdmin.cargarEnTabla(sr));

        }

        gestorAdmin.desconectarBD();
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JComboBox cboTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfEmail;
    public static javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPass;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfUser;
    private javax.swing.JLabel tvID;
    // End of variables declaration//GEN-END:variables


 private String validarDatos() {
        String msg = "";

        if (tfID.getText().equals("")) {
            msg += "Por favor digite la identificacion del cliente\n";
        } else if (!IsNumero(tfID.getText())) {
            msg += "Por favor digite la identificacion del cliente solo con numeros\n";
        }
        if (tfNombre.getText().equals("")) {
            msg += "Por favor digite el nombre del usuario "+" "+""+tfID.getText()+"\n";
        }
         
        if (lbl.getText().equals("")) {
            msg += "Por favor seleccione el roll que va a desempeñar el usuario "+" "+""+tfNombre.getText()+"\n";
        }
        if (tfApellido.getText().equals("")) {
            msg += "Por favor digite los apellidos del usuario "+" "+""+tfNombre.getText()+"\n";
        }
        if (tfEmail.getText().equals("")) {
            msg += "Por favor digite el correo electronico del usuario "+" "+""+tfNombre.getText()+"\n";
        }else if (validateEmail(tfEmail.getText())==false) {
          msg += "Verifique el correo electronico ya que no coincide con el formato conocido \n";
        }
          
        if (tfTelefono.getText().equals("")) {
            msg += "Por favor digite el # de telefono del usuario "+" "+""+tfNombre.getText()+"\n";
        } else if (validateTelephone(tfTelefono.getText())==false) {
            msg += "Escriba el numero de telefono en el siguiente formato: xxxx-xxxx, no olvide el guión \n";
        }
        if (tfUser.getText().equals("")) {
            msg += "Por favor digite el nombre de la cuenta del usuario "+" "+""+tfNombre.getText()+"\n";
        }
        if (tfPass.getText().equals("")) {
            msg += "Por favor digite la contraseña del usuario "+" "+""+tfNombre.getText()+"\n";
        }
        return msg;
    }


  boolean IsNumero(String dato)
 {
        try {
            int num = Integer.parseInt(dato);
            return true;

        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
    private static final String EMAIL_PATTERN = 
			"^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
			+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
 
 public static boolean validateEmail(String email) {
	try{
	    // Compiles the given regular expression into a pattern.
	    Pattern pattern = Pattern.compile(EMAIL_PATTERN);
	    // Match the given input against this pattern
	    Matcher matcher = pattern.matcher(email);
	    return matcher.matches();
	}catch(Exception e){
		e.printStackTrace();
	}
	return false;
}
     private static final String TELEPHONE_PATTERN = 
			"^([0-9]{4})*-"
             +          "[0-9]{4}$";
 
 public static boolean validateTelephone(String telephone) {
	try{
	    // Compiles the given regular expression into a pattern.
	    Pattern pattern = Pattern.compile(TELEPHONE_PATTERN);
	    // Match the given input against this pattern
	    Matcher matcher = pattern.matcher(telephone);
	    return matcher.matches();
	}catch(Exception e){
		e.printStackTrace();
	}
	return false;
}
}
