/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ui;





import static Ui.frmHorarios.tblJornada;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import logic.clsGestorJornada;
import logic.clsJornadas;


/**
 *
 * @author INVENIO122
 */
public class frmAgregarJornadas extends javax.swing.JFrame {
    clsGestorJornada gestor;
    clsJornadas jornada;
    /**
     * Creates new form frmAgregarJornadas
     */
    public frmAgregarJornadas() {
        initComponents();
     gestor = new clsGestorJornada();
         
        jornada = null;
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        cbHora = new javax.swing.JComboBox();
        cbMinuto = new javax.swing.JComboBox();
        cbPeriodo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbHoraSa = new javax.swing.JComboBox();
        cbMinutoSa = new javax.swing.JComboBox();
        cbPeriodoSa = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Turnos Laborales");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " GESTION DE DATOS ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 255, 0)));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Hora Inicio ");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Tiempo");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Hora Salida ");

        txtTiempo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        cbHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01","02", "03", "04","05","06","07","08","09","10","11","12" }));

        cbMinuto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "00","05", "10", "15","20","25","30","35","40","45","50","55" }));

        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "am","pm"}));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText(":");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText(":");

        cbHoraSa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01","02", "03", "04","05","06","07","08","09","10","11","12" }));
        cbHoraSa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHoraSaItemStateChanged(evt);
            }
        });

        cbMinutoSa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "00","05", "10", "15","20","25","30","35","40","45","50","55" }));

        cbPeriodoSa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "am","pm"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbHoraSa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMinutoSa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPeriodoSa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbHoraSa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbMinutoSa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPeriodoSa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (validarCampos().equals("")){
        String horaInicio;
       String horaSalida;
        String hora;
        String minuto;
        String periodo;
        String horaSa;
        String minutoSa;
        String periodoSa;
        jornada = new clsJornadas();
        
        hora = cbHora.getSelectedItem().toString();
 minuto = cbMinuto.getSelectedItem().toString();
  periodo = cbPeriodo.getSelectedItem().toString();
        
         horaSa = cbHoraSa.getSelectedItem().toString();
 minutoSa = cbMinutoSa.getSelectedItem().toString();
  periodoSa = cbPeriodoSa.getSelectedItem().toString();
  
  horaInicio = hora +":"+minuto+" "+periodo;
  horaSalida = horaSa +":"+minutoSa+" "+periodoSa;
  
  
  
        jornada.setTiempo(txtTiempo.getText());
jornada.setHoraInicio(horaInicio);
jornada.setHoraSalida(horaSalida);

 

                                          

  gestor.agregarjornada(jornada); 
    
//   cargar(); 

JOptionPane.showMessageDialog(rootPane, "Datos guardados exitosamente");

this.dispose();

       }else{
       JOptionPane.showMessageDialog(rootPane, validarCampos());
       }

        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbHoraSaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHoraSaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHoraSaItemStateChanged

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
           
        
        gestor.conectarBD();
        ResultSet rs = gestor.cargarJornadas();
        if (rs != null) {
            tblJornada.setModel(gestor.cargarEnTabla(rs));

        }

        gestor.desconectarBD();
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarJornadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbHora;
    private javax.swing.JComboBox cbHoraSa;
    private javax.swing.JComboBox cbMinuto;
    private javax.swing.JComboBox cbMinutoSa;
    private javax.swing.JComboBox cbPeriodo;
    private javax.swing.JComboBox cbPeriodoSa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables


//public void cargar (){
//
//frmHorarios f = new frmHorarios();
// gestor.conectarBD();
//        ResultSet rs = gestor.cargarJornadas();
//        if (rs != null) {
//            f.tblJornada.setModel(gestor.cargarEnTabla(rs));
//
//} 
//
//
//}

    private String validarCampos(){
    
    String alert = "";
    
    if (txtTiempo.getText().equals("")){
    
    alert += "Por favor escriba un nombre que identifique este turno \n ";
    }
    if (cbHora.getSelectedItem().toString().equals("")){
    alert += "Por favor seleccione una hora de entrada para el turno de "+" "+""+txtTiempo.getText()+"\n";
    }
     if (cbMinuto.getSelectedItem().toString().equals("")){
    alert += "Por favor seleccione los minutos de entrada para el turno de "+" "+""+txtTiempo.getText()+"\n";
    }
     if (cbPeriodo.getSelectedItem().toString().equals("")){
    alert += "Por favor seleccione si la hora de entrada es am o pm para el turno de "+" "+""+txtTiempo.getText()+"\n";
    }  
     if (cbHoraSa.getSelectedItem().toString().equals("")){
    alert += "Por favor seleccione una hora de salida para el turno de "+" "+""+txtTiempo.getText()+"\n";
    }
      if (cbMinutoSa.getSelectedItem().toString().equals("")){
    alert += "Por favor seleccione los minutos de salida para el turno de "+" "+""+txtTiempo.getText()+"\n";
    }
        if (cbPeriodoSa.getSelectedItem().toString().equals("")){
    alert += "Por favor seleccione si la hora de salida es am o pm para el turno de "+" "+""+txtTiempo.getText()+"\n";
    }
    return alert;
    }
    
}
