/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author INVENIO122
 */
public class frmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        btnAgregarUsuarios = new javax.swing.JButton();
        btnControl = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnControl1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar6.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar6.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INVENIO TRAINING CENTER");

        jToolBar1.setRollover(true);

        jToolBar2.setRollover(true);

        btnAgregarUsuarios.setIcon(new javax.swing.ImageIcon("C:\\wamp\\tutorias\\AplicacionCodigoBarras\\src\\Img\\1406007660_icon-person-add.png")); // NOI18N
        btnAgregarUsuarios.setToolTipText("Agregar Empleados");
        btnAgregarUsuarios.setFocusable(false);
        btnAgregarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuariosActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAgregarUsuarios);

        btnControl.setIcon(new javax.swing.ImageIcon("C:\\wamp\\tutorias\\AplicacionCodigoBarras\\src\\Img\\1406003272_view-process-users.png")); // NOI18N
        btnControl.setToolTipText("Control");
        btnControl.setFocusable(false);
        btnControl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnControl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlActionPerformed(evt);
            }
        });
        jToolBar2.add(btnControl);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\wamp\\tutorias\\AplicacionCodigoBarras\\src\\Img\\1403779442_Timetable.png")); // NOI18N
        jButton2.setToolTipText("Horarios");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        btnControl1.setIcon(new javax.swing.ImageIcon("C:\\wamp\\tutorias\\AplicacionCodigoBarras\\src\\Img\\Report.png")); // NOI18N
        btnControl1.setToolTipText("Reportes");
        btnControl1.setFocusable(false);
        btnControl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnControl1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnControl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControl1ActionPerformed(evt);
            }
        });
        jToolBar2.add(btnControl1);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\wamp\\tutorias\\AplicacionCodigoBarras\\src\\Img\\Key.png")); // NOI18N
        jButton1.setToolTipText("Gestionar Clave de Cierre");
        jButton1.setActionCommand("fsfs");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\wamp\\tutorias\\AplicacionCodigoBarras\\src\\Img\\1403779645_sign-out.png")); // NOI18N
        jButton6.setToolTipText("Salir");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton6);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel1.setText("Usuario");

        lblName.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 255, 0));

        lbltipo.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lbltipo.setText("Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int resp = JOptionPane.showConfirmDialog(rootPane, "" + lblName.getText() + " ¿Está seguro de salir?",
                "ADVERTENCIA¡¡¡¡¡¡", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            new frmLogin().setVisible(true);
            this.dispose();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frmHorarios fp = new frmHorarios();
        // fp.show();
        if (!esAbierta(fp.getClass())) {
            fp.show();
            centrar(fp);
            jDesktopPane1.add(fp);
            try {
                fp.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.err.println(ex.getMessage());
            }
        } else {
            fp = null;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuariosActionPerformed
        infrmAgregar fr = new infrmAgregar();

        // fp.show();
        if (!esAbierta(fr.getClass())) {
            fr.show();
            centrar(fr);
            jDesktopPane1.add(fr);
            try {
                fr.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.err.println(ex.getMessage());
            }
        } else {
            fr = null;
        }
    }//GEN-LAST:event_btnAgregarUsuariosActionPerformed

    private void btnControl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControl1ActionPerformed

        frmReportes fr = new frmReportes();

        // fp.show();
        if (!esAbierta(fr.getClass())) {
            fr.show();
            centrar(fr);
            jDesktopPane1.add(fr);
            try {
                fr.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.err.println(ex.getMessage());
            }
        } else {
            fr = null;
        }
    }//GEN-LAST:event_btnControl1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmClave fr = new frmClave();

        // fp.show();
        if (!esAbierta(fr.getClass())) {
            fr.show();
            centrar(fr);
            jDesktopPane1.add(fr);
            try {
                fr.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.err.println(ex.getMessage());
            }
        } else {
            fr = null;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlActionPerformed

        frmHrasTrab rf = new frmHrasTrab();

        // fp.show();
        if (!esAbierta(rf.getClass())) {
            rf.show();
            centrar(rf);
            jDesktopPane1.add(rf);
            try {
                rf.setSelected(true);
            } catch (PropertyVetoException ex) {
                System.err.println(ex.getMessage());
            }
        } else {
            rf = null;
        }
    }//GEN-LAST:event_btnControlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuarios;
    private javax.swing.JButton btnControl;
    private javax.swing.JButton btnControl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public static javax.swing.JLabel lblName;
    private javax.swing.JLabel lbltipo;
    // End of variables declaration//GEN-END:variables

    private boolean esAbierta(Object ventana) {
        boolean abierta = false;
        JInternalFrame objetos[] = jDesktopPane1.getAllFrames();

        for (JInternalFrame v : objetos) {
            if (v.getClass().equals(ventana)) {
                abierta = true;

                try {
                    v.setSelected(true);
                } catch (PropertyVetoException ex) {
                    System.err.println(ex.getMessage());
                }
                break;
            }
        }
        return abierta;
    }

    public void centrar(JInternalFrame ventana) {
        int x = (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth() / 2 - ventana.getWidth() / 2);
        int y = (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() / 2 - ventana.getHeight() / 2);
        ventana.setLocation(x, 0);
    }

}
