/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ui;

import java.sql.ResultSet;
import logic.clsGestorEmpleado;
import logic.clsGestorHorarios;
import javax.swing.JOptionPane;
/**
 *
 * @author INVENIO122
 */
public class frmEmpleadoHorarios extends javax.swing.JInternalFrame {
 clsGestorHorarios gestorhora;
    ResultSet rs;
    clsGestorEmpleado gestor;
    /**
     * Creates new form frmEmpleadoHorarios
     */
    public frmEmpleadoHorarios() {
         gestorhora = new clsGestorHorarios();
           gestor =  new clsGestorEmpleado();
        initComponents();
       
        rs = null;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarioEmpleado = new javax.swing.JTable();
        cbBuscar = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestion de Horarios Laborales");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblHorarioEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblHorarioEmpleado);

        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Turno", "Fecha Inicio", "Fecha Fin" }));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Filtrar todos los(as) ");

        txtBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
              String cedula;
  
cedula = frmEmpleado.lbltipo.getText();
//        


gestor.conectarBD();
 rs = gestor.likenombre(cedula);


  tblHorarioEmpleado.setModel(gestor.cargarEnTabla(rs));  
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       if(validarBuscador().equals("")){
        String selected;
        String ps = "";
        selected = cbBuscar.getSelectedItem().toString();
        if (selected == "Turno"){
            ps= "j.tiempo";
        }
        if (selected == "Fecha Inicio"){
            ps= "DATE_FORMAT(h.fechaInicio,'%d/%m/%Y')";
        }
        if (selected == "Fecha Fin"){
            ps= "DATE_FORMAT(h.fechaFinal,'%d/%m/%Y')";
        }
      
        gestor.conectarBD();
        String buscar;
        String id;
        
        id = frmEmpleado.lbltipo.getText();
        buscar = txtBuscar.getText();
        if (ps=="j.tiempo"){

            rs = gestor.likeHorario(buscar, ps, id);
        }
        if (ps=="DATE_FORMAT(h.fechaInicio,'%d/%m/%Y')"){

            rs = gestor.likeHorario(buscar, ps, id);
        }
        if (ps=="DATE_FORMAT(h.fechaFinal,'%d/%m/%Y')"){

            rs = gestor.likeHorario(buscar, ps, id);
        }

        tblHorarioEmpleado.setModel(gestor.cargarEnTabla(rs));
        
        
       }else{
       
       JOptionPane.showMessageDialog(rootPane, validarBuscador());
       }
        
        
        
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblHorarioEmpleado;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables



//  private void cargarHorarios() {
//        
//         gestorhora.conectarBD();
//        ResultSet rs = gestorhora.cargarHorarios();
//        if (rs != null) {
//            tblHorarioEmpleado.setModel(gestorhora.cargarEnTabla(rs));
//new frmHorarios().show();
//        }
//
//        gestorhora.desconectarBD();
//        
//        
//    }

private String validarBuscador(){
String alert = "";

if (cbBuscar.getSelectedItem().toString().equals("")) {
            alert += "Por favor seleccione el criterio de busqueda \n";
        }


return alert;}

}
