/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import logic.clsGestorHorarios;
import logic.clsGestorJornada;

/**
 *
 * @author INVENIO122
 */
public class frmHorarios extends javax.swing.JInternalFrame {
    clsGestorJornada gestor; 
    clsGestorHorarios gestorhora;
    ResultSet rs;
    frmEditarJornada editar;
    /**
     * Creates new form frmHorarios
     */
    public frmHorarios() {
        gestor = new clsGestorJornada();
        gestorhora = new clsGestorHorarios();
        initComponents();
        rs = null;
        editar = new frmEditarJornada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popHorarios = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Horarios = new javax.swing.JPopupMenu();
        EliminarHorario = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btAgregarHorarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cboBuscar = new javax.swing.JComboBox();
        txtBuscar1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        cbBuscar = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJornada = new javax.swing.JTable();

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        popHorarios.add(Editar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popHorarios.add(Eliminar);

        EliminarHorario.setText("Eliminar Horario");
        EliminarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarHorarioActionPerformed(evt);
            }
        });
        Horarios.add(EliminarHorario);

        setClosable(true);
        setMaximizable(true);
        setTitle("Horarios Laborales");
        setAlignmentX(0.9F);
        setAlignmentY(0.9F);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        btAgregarHorarios.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btAgregarHorarios.setText("Agregar Horarios");
        btAgregarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarHorariosActionPerformed(evt);
            }
        });

        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblHorarios.setComponentPopupMenu(Horarios);
        jScrollPane1.setViewportView(tblHorarios);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Filtrar todos los(as) ");

        cboBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Cedula","Nombre", "Fecha Inicio", "Fecha Fin" }));

        txtBuscar1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscar1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btAgregarHorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 483, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Horarios Empleados", jPanel2);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Gestionar Turnos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Turno", "Hora Inicio", "Hora Salida" }));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Filtrar todos los(as) ");

        tblJornada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblJornada.setComponentPopupMenu(popHorarios);
        jScrollPane2.setViewportView(tblJornada);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Turnos Laborales", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
      new frmAgregarJornadas().show();
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if (validarBuscadorJornadas().equals("")){
        String selected;
        String ps = "";
        selected = cbBuscar.getSelectedItem().toString();
        if (selected == "Turno"){
            ps= "tiempo";
        }
        if (selected == "Hora Inicio"){
            ps= "horaInicio";
        }
        if (selected == "Hora Salida"){
            ps= "horaSalida";
        }
      
        gestor.conectarBD();
        String buscar;
        buscar = txtBuscar.getText();
        if (ps=="tiempo"){

            rs = gestor.likeTurno(buscar, ps);
        }
        if (ps=="horaInicio"){

            rs = gestor.likeTurno(buscar, ps);
        }
        if (ps=="horaSalida"){

            rs = gestor.likeTurno(buscar, ps);
        }

        tblJornada.setModel(gestor.cargarEnTabla(rs));}
        else{
        JOptionPane.showMessageDialog(rootPane, validarBuscadorJornadas());
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
          int selected = tblJornada.getSelectedRow();
        boolean id1;
        String ids;
        int iden;
        boolean ss;
        id1 = editar.isShowing();
        if (id1==false) {
            if (tblJornada.getSelectedRow()>-1) {

                ids=tblJornada.getValueAt(tblJornada.getSelectedRow(), 0).toString();
                gestor.conectarBD();
                iden = Integer.parseInt(ids);
                rs = gestor.buscarporid(iden);
                try {
                    if (rs.next()) {
                        frmEditarJornada.lblId.setText(ids);
                        editar.setVisible(true);
                       
                    } else{
                        JOptionPane.showMessageDialog(rootPane, "Problemas al cargar el numero de turno");
                    }

                } catch (HeadlessException | SQLException e) {
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Por favor seleccione la jornada que desea editar en la tabla");
            }

        }
        else {
            id1 = true;
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       if (tblJornada.getSelectedRow()>-1){
    String id = tblJornada.getValueAt(tblJornada.getSelectedRow(), 0).toString();
    System.out.println(id);
            int resp = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de eliminar la jornada "+id+ "?",
                "¡¡¡ADVERTENCIA!!!",JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_OPTION){
            
        
    
    gestor.eliminar(Integer.parseInt(id));
        cargarDatos();}
}
    }//GEN-LAST:event_EliminarActionPerformed

    private void btAgregarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarHorariosActionPerformed
        new frmAgregarHorarios().show();
    }//GEN-LAST:event_btAgregarHorariosActionPerformed

    private void EliminarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarHorarioActionPerformed
            if (tblHorarios.getSelectedRow()>-1){
    String id = tblHorarios.getValueAt(tblHorarios.getSelectedRow(), 0).toString();
    System.out.println(id);
            int resp = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de eliminar el horario "+id+ "?",
                "¡¡¡ADVERTENCIA!!!",JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_OPTION){
            
        
    
    gestorhora.eliminar(Integer.parseInt(id));
        cargarHorarios();}
}
    }//GEN-LAST:event_EliminarHorarioActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       cargarDatos();
       cargarHorarios();
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtBuscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar1KeyReleased
       
        
        if(validarBuscadorHorarios().equals("")){
        String selected;
        String ps = "";
        selected = cboBuscar.getSelectedItem().toString();
        if (selected == "Cedula"){
            ps= "u.idusuario";
        }
        if (selected == "Nombre"){
            ps= "u.nombre";
        }
        if (selected == "Fecha Inicio"){
            ps= "DATE_FORMAT(h.fechaInicio,'%d/%m/%Y')";
        }
        if (selected == "Fecha Fin"){
            ps= "DATE_FORMAT(h.fechaFinal,'%d/%m/%Y')";
        }
      
        gestorhora.conectarBD();
        String buscar;
        String id;
        
       
        buscar = txtBuscar1.getText();
        if (ps=="u.idusuario"){

            rs = gestorhora.likeHorario(ps,buscar);
        }
         if (ps=="u.nombre"){

            rs = gestorhora.likeHorario(ps,buscar);
        }
        if (ps=="DATE_FORMAT(h.fechaInicio,'%d/%m/%Y')"){

            rs = gestorhora.likeHorario(ps,buscar);
        }
        if (ps=="DATE_FORMAT(h.fechaFinal,'%d/%m/%Y')"){

            rs = gestorhora.likeHorario(ps,buscar);
        }

        tblHorarios.setModel(gestorhora.cargarEnTabla(rs));
        
        
       }else{
       
       JOptionPane.showMessageDialog(rootPane, validarBuscadorHorarios());
       }
        
        
    }//GEN-LAST:event_txtBuscar1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Editar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem EliminarHorario;
    private javax.swing.JPopupMenu Horarios;
    private javax.swing.JButton btAgregarHorarios;
    private javax.swing.JComboBox cbBuscar;
    private javax.swing.JComboBox cboBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPopupMenu popHorarios;
    public static javax.swing.JTable tblHorarios;
    public static javax.swing.JTable tblJornada;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    // End of variables declaration//GEN-END:variables

 private void cargarDatos() {
        
         gestor.conectarBD();
        ResultSet sr = gestor.cargarJornadas();
        
        if (sr != null) {
            tblJornada.setModel(gestor.cargarEnTabla(sr));

        }

        gestor.desconectarBD();
        

    }
 
  private void cargarHorarios() {
        
         gestorhora.conectarBD();
        ResultSet sr = gestorhora.cargarHorarios();
        if (sr != null) {
            tblHorarios.setModel(gestorhora.cargarEnTabla(sr));

        }

        gestorhora.desconectarBD();
        
        
    }

  private String validarBuscadorJornadas(){
String alert = "";

if (cbBuscar.getSelectedItem().toString().equals("")) {
            alert += "Por favor seleccione el criterio de busqueda \n";
        }


return alert;}
 private String validarBuscadorHorarios(){
String alert = "";

if (cboBuscar.getSelectedItem().toString().equals("")) {
            alert += "Por favor seleccione el criterio de busqueda \n";
        }


return alert;}
}
