/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import logic.GestorDatos;
import logic.clsDatos;
import logic.clsInfo;
import logic.clsReloj;
import logic.clsValidacionEntrada;

/**
 *
 * @author invenio_110
 */
public class frmInterfaz extends javax.swing.JFrame {

    GestorDatos gestorDatos;
    clsInfo info;
    clsDatos dato;
    clsValidacionEntrada vali;
    ResultSet rs;

    /**
     * Creates new form frmInterfaz
     */
    public frmInterfaz() {
        initComponents();
        rs = null;
        clsReloj Nuevo = new clsReloj(lblReloj);
        Nuevo.start();
        gestorDatos = new GestorDatos();
        vali = new clsValidacionEntrada();
        info = null;
        dato = null;
        lblFecha.setText(fechaActual());
        txtNombre.setEditable(false);
        txtCodigo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        lblReloj1 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INVENIO TRAINING CENTER");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bienvenido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 0, 14), java.awt.Color.lightGray)); // NOI18N

        txtCodigo.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Identificacion");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora y Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 0, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        lblFecha.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(153, 153, 153));

        lblReloj.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(153, 153, 153));

        lblReloj1.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        lblReloj1.setForeground(new java.awt.Color(153, 153, 153));
        lblReloj1.setText("INVENIO TRAINING CENTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(lblReloj1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblReloj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(lblReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Key.png"))); // NOI18N
        btnIngresar.setToolTipText("Ingresar al Sistema");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/1402344177_exit.png"))); // NOI18N
        btnSalir.setToolTipText("Cerrar Sistema");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNombre)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if (!txtCodigo.getText().equals("")) {
            //      ---------Busca-------------------------
            int codigo=0;
            try{
                codigo = Integer.parseInt(txtCodigo.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane, "En la identificacion solo se aceptan numeros");
                codigo=0;
            }
            
            info = gestorDatos.buscarDato(codigo);
            vali = gestorDatos.validacion(codigo);
            
            if (info != null) {
                txtNombre.setText(info.getNombre() + " " + info.getApellidos());
                //      ----------------Guarda el Codigo Fecha y Hora-----------------------
                dato = new clsDatos();
                dato.setCodigo(Integer.parseInt(txtCodigo.getText()));
                dato.setFecha(lblFecha.getText() + " " + lblReloj.getText());

//            JOptionPane.showMessageDialog(rootPane, dato.getFecha());
                if (gestorDatos.guardarDato(dato) != false) {

                    Date uno = new Date();
//   este no   uno = dcInicio.getCalendar().getTime();
//    no  dos = dcFinal.getCalendar().getTime();

                    SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
                    String fecha1 = sdf.format(uno);

                    if (vali.getHora() != null) {

                        JOptionPane.showMessageDialog(rootPane, info.getNombre() + " " + info.getApellidos() + " " + " su salida ha sido registrada exitosamente a las " + lblReloj.getText() + " el dia " + fecha1);
//ja.setText(vali.getHora());
                    } else {

                        JOptionPane.showMessageDialog(rootPane, info.getNombre() + " " + info.getApellidos() + " " + " su entrada ha sido registrada exitosamente a las " + lblReloj.getText() + " el dia " + fecha1);
//        ja.setText(vali.getHora());
                    }
                    limpiarCampos();
                    txtCodigo.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar guardar ");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Empleado no encontrado, por favor verifique su identificacion",
                        "Buscar empleado", JOptionPane.ERROR_MESSAGE);
                limpiarCampos();
            }
            txtCodigo.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        new frmLogin().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        String codigo = "";
        String clave = "";
        int resp = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de cerrar el sistema Invenio Training Center?",
                "ADVERTENCIA¡¡¡¡¡¡", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            clave = JOptionPane.showInputDialog("Digite el código de seguridad");
            gestorDatos.conectarBD();

            ResultSet rs = gestorDatos.seleccionar("select codigosalida from tblsalida");
            try {
                if (rs.next()) {
                    codigo = rs.getString(1);
                }
            } catch (Exception e) {
            }
            gestorDatos.desconectarBD();
            if (clave.equals(codigo)) {

                System.exit(1);
            } else {

                JOptionPane.showMessageDialog(rootPane, "Código de seguridad incorrecto, por favor verifiquelo y vuelva a intentar",
                        "Código incorrecto", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    public static String fechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
        return formateador.format(fecha);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblReloj1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
private void limpiarCampos() {

        txtNombre.setText("");
        txtCodigo.setText("");
        ;
    }
}
