/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Logic.clsLogin;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import logic.clsGestorLogin;

/**
 *
 * @author Hp
 */
public class frmLogin extends javax.swing.JFrame {

//    clsLogin login;
    clsGestorLogin gestorLogin;
    ResultSet rs;
    String nombre;
    ResultSet rs2;
    String name;

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        // Central el form y ponerle el icono diferente 
        this.setLocationRelativeTo(null);
        URL url = getClass().getResource("/Img/clientes.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        gestorLogin = new clsGestorLogin();
        rs = null;
        rs2 = null;
        txtNick.setHorizontalAlignment(SwingConstants.CENTER);
        txtPass.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        btnSupervisor = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Validación de acceso");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setName("frmLogin"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña");

        txtNick.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNick.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));
        txtNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNickActionPerformed(evt);
            }
        });

        btnSupervisor.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnSupervisor.setText("Accesar");
        btnSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupervisorActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\wamp\\tutorias\\AplicacionCodigoBarras\\src\\Img\\clientes.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSupervisor)
                            .addComponent(btnSalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
//               int resp = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de salir?",
//                "Salir",JOptionPane.YES_NO_OPTION);
//        if(resp == JOptionPane.YES_OPTION){

        new frmInterfaz().setVisible(true);
        this.dispose();
//        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupervisorActionPerformed


        if (validarDatos().equals("")) {
            String usuario;
            String pass;
            pass = null;
            usuario = "";
            usuario = txtNick.getText();
            pass = txtPass.getText();
//            login = new clsLogin();
//            JOptionPane.showMessageDialog(rootPane, "0");
            try {
                gestorLogin.conectarBD();
//                JOptionPane.showMessageDialog(rootPane, "1");
                rs = gestorLogin.loginadmin(usuario, pass);
//                JOptionPane.showMessageDialog(rootPane, "2");
                if (rs.next()) {
//                    JOptionPane.showMessageDialog(rootPane, "3");
                    int tipo = rs.getInt("idTipoUsuario");
                    if (tipo == 1) {
                        nombre = rs.getString("nombre");
                        String apellido = rs.getString("apellidos");
                        String nombreUsuario = nombre + " " + apellido;
//                        JOptionPane.showMessageDialog(rootPane, "admin");
                        new frmAdministrador().setVisible(true);
                        frmAdministrador.lblName.setText(nombreUsuario);
                        this.dispose();

                    }

                    if (tipo == 2) {
//                        JOptionPane.showMessageDialog(rootPane, "user");
                        String cedula = rs.getString("idUsuario");
                        name = rs.getString("nombre");

                        String apellido = rs.getString("apellidos");

                        String nombre_completo = name + " " + apellido;

                        new frmEmpleado().setVisible(true);
                        frmEmpleado.lblName.setText(nombre_completo);
                        frmEmpleado.lbltipo.setText(cedula);
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cuenta incorrecta, verifique sus credenciales e intente de nuevo");
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.toString());
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, validarDatos());
      }

    }//GEN-LAST:event_btnSupervisorActionPerformed

    private void txtNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNickActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmLogin().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSupervisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNick;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    private String validarDatos() {
        String mensaje = "";
        if (txtNick.getText().equals("")) {
            mensaje += "Por favor digite su Usuario \n";
        }
        if (txtPass.getText().equals("")) {
            mensaje += "Por favor digite su password \n";
        }
        return mensaje;
    }//=========================================================================

     //=========================================================================
}
